export const FORM_ERROR_KEYS = [
  "fullNameRequired",
  "fullNameInvalid",
  "businessEmailRequired",
  "businessEmailInvalid",
  "aboutProjectTooLong",
  "budgetRequired",
  "servicesRequired",
  "phoneRequired",
  "phoneInvalid",
  "messageTooShort",
  "messageRequired",
  "emailRequired",
  "emailInvalid",
  "websiteInvalid",
  "websiteRequired",
  "contactRequired",
  "databaseSizeRequired",
  "monthlyVisitorsRequired",
  "woocommerceRequired",
  "passwordRequired",
  "passwordTooShort",
  "passwordMismatch",
  "otpRequired",
  "otpInvalid",
  "nationalIdRequired",
  "nationalIdInvalid",
  "birthDateRequired",
  "mobileRequired",
  "mobileInvalid",
  "mobileBelongsRequired",
  "provinceRequired",
  "cityRequired",
  "addressRequired",
  "addressTooLong",
  "postalCodeRequired",
  "postalCodeInvalid",
  "attestationRequired",
  "documentRequired",
  "documentInvalid",
] as const;

export type FormErrorKey = (typeof FORM_ERROR_KEYS)[number];

export const errorKey = (key: FormErrorKey) => key;
