import type { Metadata } from "next";
import { hasLocale } from "next-intl";

import { LocaleType } from "@/types/intl.types";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";
import { getDirection } from "@/lib/i18n";
import { DirectionProvider } from "../../components/ui/direction";
import { kalamehFont, YekanBakhFont } from "@/lib/fonts";
import Providers from "@/providers/providers";

import "overlayscrollbars/overlayscrollbars.css";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type Props = {
  params: Promise<{ locale: "en" | "fa" }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const locale = (await params)?.locale;
  const isFa = locale === "fa";

  const title = isFa
    ? "یونیکسی | زیرساخت مدیریت‌شده و خدمات فنی"
    : "Unixsee | Managed Infrastructure & Technical Services";

  const description = isFa
    ? "ارائه خدمات میزبانی مدیریت‌شده، بهینه‌سازی عملکرد و مشاوره فنی برای کسب‌وکارهای مدرن."
    : "Managed hosting, performance optimization, and technical consulting for modern businesses.";

  return {
    title,
    description,
    // icons: {
    //   icon: [
    //     {
    //       url: "/logo.png",
    //       media: "(prefers-color-scheme: light)",
    //     },
    //     {
    //       url: "/logo.png",
    //       media: "(prefers-color-scheme: dark)",
    //     },
    //   ],
    // },
    alternates: {
      canonical: isFa ? "/fa" : "/",
      languages: {
        en: "/en",
        fa: "/fa",
      },
    },
    openGraph: {
      title,
      description,
      locale: isFa ? "fa_IR" : "en_US",
      siteName: "Unixsee",
    },
  };
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = (await params) as { locale: LocaleType };

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const direction = getDirection(locale);

  setRequestLocale(locale);

  const lang = locale === "en" ? "en" : "fa";

  return (
    <html
      // data-overlayscrollbars-initialize
      lang={lang}
      dir={direction}
      suppressHydrationWarning
      className={`${YekanBakhFont.variable} ${kalamehFont.variable} antialiased`}
    >
      <body
        // data-overlayscrollbars-initialize
        suppressHydrationWarning
        className="flex min-h-full flex-col"
      >
        <Providers>
          <DirectionProvider dir={direction} direction={direction}>
            {children}
          </DirectionProvider>
        </Providers>
      </body>
    </html>
  );
}
